In [1]:
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\hp\Downloads\Case+Study+Notebook\Case Study Notebook\googleplaystore_v2.csv")

In [3]:
# Print 5 rows from starting
data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700.0,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800.0,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

# Data Cleaning

In [5]:
# Check for any missing values
data.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [6]:
# Checking data type of all columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  float64
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(2), object(11)
memory usage: 1.1+ MB

# Handling missing values

In [7]:
# We observed that Rating column has 1474 missing values.
# so we will remove those values from our data set.

In [8]:
# Check the missing values in Rating column.
data.Rating.isnull()

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838     True
10839    False
10840    False
Name: Rating, Length: 10841, dtype: bool

In [9]:
# Dropping the missing rows in Rating column.
data1=data[-data.Rating.isnull()]
data1.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700.0,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800.0,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [10]:
# Check the size of both of the data frames
print(data.shape)
print(data1.shape)

(10841, 13)
(9367, 13)

In [11]:
# Again check for missing value in the dataframe
data1.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    1
Genres            0
Last Updated      0
Current Ver       4
Android Ver       3
dtype: int64

In [12]:
# Check for null values in Current ver column.
data1[data1["Current Ver"].isnull()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
15,Learn To Draw Kawaii Characters,ART_AND_DESIGN,3.2,55,2700.0,"5,000+",Free,0,Everyone,Art & Design,"June 6, 2018",NaN,4.2 and up
1553,Market Update Helper,LIBRARIES_AND_DEMO,4.1,20145,11.0,"1,000,000+",Free,0,Everyone,Libraries & Demo,"February 12, 2013",NaN,1.5 and up
6322,Virtual DJ Sound Mixer,TOOLS,4.2,4010,8700.0,"500,000+",Free,0,Everyone,Tools,"May 10, 2017",NaN,4.0 and up
7333,Dots puzzle,FAMILY,4.0,179,14000.0,"50,000+",Paid,$0.99,Everyone,Puzzle,"April 18, 2018",NaN,4.0 and up

In [13]:
# Since only 4 values are missing, so we will replace the missing values with the most comman Current ver .

In [14]:
# Check for most comman current version
data1["Current Ver"].value_counts()

Varies with device    1415
1.0                    458
1.1                    195
1.2                    126
1.3                    120
                      ...
2.131                    1
5.9.4.0                  1
1.12.0.1654              1
3.1.50                   1
1.55                     1
Name: Current Ver, Length: 2639, dtype: int64

In [15]:
# We observed that "Varies with device" is the most cooman current version.
# so we will replace missing values with Varies with device.

In [17]:
data1["Current Ver"]=data1["Current Ver"].fillna(data1["Current Ver"].mode()[0])

<ipython-input-17-71b53e2104f4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1["Current Ver"]=data1["Current Ver"].fillna(data1["Current Ver"].mode()[0])

In [19]:
data1[data1["Current Ver"].isnull()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [28]:
# We have filled all the missing values in the Current ver column.
data1.shape

(9367, 13)

In [29]:
# Again check for missing values
data1.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    1
Genres            0
Last Updated      0
Current Ver       0
Android Ver       3
dtype: int64

In [30]:
# We are checking for missing value in content rating column.
data1[data1["Content Rating"].isnull()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,21516.529524,Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [31]:
# Removing the missing row .
data2=data1[-data1["Content Rating"].isnull()]
data2.shape

(9366, 13)

In [33]:
# Checking for null values again.
data2.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       2
dtype: int64

In [34]:
# Checking for null values in Android version column.
data2[data2["Android Ver"].isnull()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4453,[substratum] Vacuum: P,PERSONALIZATION,4.4,230,11000.0,"1,000+",Paid,$1.49,Everyone,Personalization,"July 20, 2018",4.4,NaN
4490,Pi Dark [substratum],PERSONALIZATION,4.5,189,2100.0,"10,000+",Free,0,Everyone,Personalization,"March 27, 2018",1.1,NaN

In [37]:
# Checking for most popular Android version.
data2["Android Ver"].value_counts()

4.1 and up            2059
Varies with device    1319
4.0.3 and up          1240
4.0 and up            1131
4.4 and up             875
2.3 and up             582
5.0 and up             535
4.2 and up             338
2.3.3 and up           240
3.0 and up             211
2.2 and up             208
4.3 and up             207
2.1 and up             113
1.6 and up              87
6.0 and up              48
7.0 and up              41
3.2 and up              31
2.0 and up              27
5.1 and up              18
1.5 and up              16
3.1 and up               8
2.0.1 and up             7
4.4W and up              6
8.0 and up               5
7.1 and up               3
5.0 - 8.0                2
1.0 and up               2
4.0.3 - 7.1.1            2
5.0 - 6.0                1
7.0 - 7.1.1              1
4.1 - 7.1.1              1
Name: Android Ver, dtype: int64

In [40]:
# Replace the missing values with "4.1 and up".
data2["Android Ver"]=data2["Android Ver"].fillna(data2["Android Ver"].mode()[0])

<ipython-input-40-7c1b33f22718>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["Android Ver"]=data2["Android Ver"].fillna(data2["Android Ver"].mode()[0])

In [41]:
# Checking for missing values again in the dataframe.
data2.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [44]:
# Observing the shape of the dataframes.
print(data.shape)
print(data1.shape)
print(data2.shape)

(10841, 13)
(9367, 13)
(9366, 13)

In [45]:
# SO far we have handled the missing values from the dataset.

# Handling incorrect datatypes

In [46]:
# Check for datatypes of the columns.
data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9366 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9366 non-null   object
 1   Category        9366 non-null   object
 2   Rating          9366 non-null   float64
 3   Reviews         9366 non-null   object
 4   Size            9366 non-null   float64
 5   Installs        9366 non-null   object
 6   Type            9366 non-null   object
 7   Price           9366 non-null   object
 8   Content Rating  9366 non-null   object
 9   Genres          9366 non-null   object
 10  Last Updated    9366 non-null   object
 11  Current Ver     9366 non-null   object
 12  Android Ver     9366 non-null   object
dtypes: float64(2), object(11)
memory usage: 1.0+ MB

In [48]:
# Observing price column.
data2["Price"].value_counts()

0         8719
$2.99      114
$0.99      107
$4.99       70
$1.99       59
          ...
$39.99       1
$1.50        1
$2.50        1
$2.90        1
$1.61        1
Name: Price, Length: 73, dtype: int64

In [49]:
# Since the price sould be in numerical format , so we are making the necessary changes.

In [51]:
data2["Price"]=data2["Price"].apply(lambda x: 0 if x=="0" else float(x[1:]) )

<ipython-input-51-c1ce5a148289>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["Price"]=data2["Price"].apply(lambda x: 0 if x=="0" else float(x[1:]) )

In [52]:
data2.Price.value_counts()

0.00      8719
2.99       114
0.99       107
4.99        70
1.99        59
          ...
299.99       1
1.59         1
1.61         1
3.90         1
2.90         1
Name: Price, Length: 73, dtype: int64

In [53]:
# Checking the datatype again.
data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9366 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9366 non-null   object
 1   Category        9366 non-null   object
 2   Rating          9366 non-null   float64
 3   Reviews         9366 non-null   object
 4   Size            9366 non-null   float64
 5   Installs        9366 non-null   object
 6   Type            9366 non-null   object
 7   Price           9366 non-null   float64
 8   Content Rating  9366 non-null   object
 9   Genres          9366 non-null   object
 10  Last Updated    9366 non-null   object
 11  Current Ver     9366 non-null   object
 12  Android Ver     9366 non-null   object
dtypes: float64(3), object(10)
memory usage: 1.0+ MB

In [54]:
# Checking the reviews column
data2.Reviews.value_counts()

2          83
3          78
4          74
5          74
1          67
           ..
2941        1
4450855     1
8118880     1
710         1
1604146     1
Name: Reviews, Length: 5992, dtype: int64

In [55]:
# Changing the datatype of Reviews column.

In [58]:
data2.Reviews=data2.Reviews.astype("int32")

C:\Users\hp\anaconda3\lib\site-packages\pandas\core\generic.py:5168: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [59]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9366 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9366 non-null   object
 1   Category        9366 non-null   object
 2   Rating          9366 non-null   float64
 3   Reviews         9366 non-null   int32
 4   Size            9366 non-null   float64
 5   Installs        9366 non-null   object
 6   Type            9366 non-null   object
 7   Price           9366 non-null   float64
 8   Content Rating  9366 non-null   object
 9   Genres          9366 non-null   object
 10  Last Updated    9366 non-null   object
 11  Current Ver     9366 non-null   object
 12  Android Ver     9366 non-null   object
dtypes: float64(3), int32(1), object(9)
memory usage: 987.8+ KB

In [60]:
# Making changes in Installs column.
data2["Installs"]=data2["Installs"].apply(lambda x : int(x.replace(',','').replace('+','')))

<ipython-input-60-dc16fc582a61>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["Installs"]=data2["Installs"].apply(lambda x : int(x.replace(',','').replace('+','')))

In [61]:
data2["Installs"]

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10834         500
10836        5000
10837         100
10839        1000
10840    10000000
Name: Installs, Length: 9366, dtype: int64

In [62]:
# Checking datatype once again
data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9366 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9366 non-null   object
 1   Category        9366 non-null   object
 2   Rating          9366 non-null   float64
 3   Reviews         9366 non-null   int32
 4   Size            9366 non-null   float64
 5   Installs        9366 non-null   int64
 6   Type            9366 non-null   object
 7   Price           9366 non-null   float64
 8   Content Rating  9366 non-null   object
 9   Genres          9366 non-null   object
 10  Last Updated    9366 non-null   object
 11  Current Ver     9366 non-null   object
 12  Android Ver     9366 non-null   object
dtypes: float64(3), int32(1), int64(1), object(8)
memory usage: 987.8+ KB

In [63]:
data2.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700.0,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800.0,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

# Sanity Checks

In [64]:
data2.Rating.describe()

count    9366.000000
mean        4.191757
std         0.515219
min         1.000000
25%         4.000000
50%         4.300000
75%         4.500000
max         5.000000
Name: Rating, dtype: float64

In [65]:
data2.Reviews.describe()

count    9.366000e+03
mean     5.140498e+05
std      3.144042e+06
min      1.000000e+00
25%      1.862500e+02
50%      5.930500e+03
75%      8.153275e+04
max      7.815831e+07
Name: Reviews, dtype: float64

In [66]:
data2.Size.describe()

count      9366.000000
mean      22705.733753
std       21305.040123
min           8.500000
25%        6600.000000
50%       21000.000000
75%       27000.000000
max      100000.000000
Name: Size, dtype: float64

In [67]:
data2.Installs.describe()

count    9.366000e+03
mean     1.789744e+07
std      9.123822e+07
min      1.000000e+00
25%      1.000000e+04
50%      5.000000e+05
75%      5.000000e+06
max      1.000000e+09
Name: Installs, dtype: float64

In [68]:
data2[(data2["Reviews"]>data2["Installs"])].shape

(7, 13)

In [69]:
data2[(data2["Reviews"]>data2["Installs"])]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2454,KBA-EZ Health Guide,MEDICAL,5.0,4,25000.000000,1,Free,0.00,Everyone,Medical,"August 2, 2018",1.0.72,4.0.3 and up
4663,Alarmy (Sleep If U Can) - Pro,LIFESTYLE,4.8,10249,21516.529524,10000,Paid,2.49,Everyone,Lifestyle,"July 30, 2018",Varies with device,Varies with device
5917,Ra Ga Ba,GAME,5.0,2,20000.000000,1,Paid,1.49,Everyone,Arcade,"February 8, 2017",1.0.4,2.3 and up
6700,Brick Breaker BR,GAME,5.0,7,19000.000000,5,Free,0.00,Everyone,Arcade,"July 23, 2018",1.0,4.1 and up
7402,Trovami se ci riesci,GAME,5.0,11,6100.000000,10,Free,0.00,Everyone,Arcade,"March 11, 2017",0.1,2.3 and up
8591,DN Blog,SOCIAL,5.0,20,4200.000000,10,Free,0.00,Teen,Social,"July 23, 2018",1.0,4.0 and up
10697,Mu.F.O.,GAME,5.0,2,16000.000000,1,Paid,0.99,Everyone,Arcade,"March 3, 2017",1.0,2.3 and up

In [70]:
# Selecting those apps which have more than 2 as the price
data2[data2["Price"]>2.00]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
234,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6800.000000,100000,Paid,4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39000.000000,100000,Paid,4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
290,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6800.000000,100000,Paid,4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
291,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39000.000000,100000,Paid,4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
427,Puffin Browser Pro,COMMUNICATION,4.0,18247,21516.529524,100000,Paid,3.99,Everyone,Communication,"July 5, 2018",7.5.3.20547,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10583,Florida Tides & Weather,WEATHER,3.8,30,2000.000000,1000,Paid,6.99,Everyone,Weather,"May 6, 2015",2.0.0,2.3 and up
10645,Football Manager Mobile 2018,SPORTS,3.9,11460,21516.529524,100000,Paid,8.99,Everyone,Sports,"June 27, 2018",Varies with device,4.1 and up
10679,Solitaire+,GAME,4.6,11235,21516.529524,100000,Paid,2.99,Everyone,Card,"July 30, 2018",Varies with device,Varies with device
10760,Fast Tract Diet,HEALTH_AND_FITNESS,4.4,35,2400.000000,1000,Paid,7.99,Everyone,Health & Fitness,"August 8, 2018",1.9.3,4.2 and up
10782,Trine 2: Complete Story,GAME,3.8,252,11000.000000,10000,Paid,16.99,Teen,Action,"February 27, 2015",2.22,5.0 and up

In [71]:
# Selecting only action genres apps
data2[data2["Genres"]=="Action"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1659,slither.io,GAME,4.4,5234162,21516.529524,100000000,Free,0.0,Everyone,Action,"November 14, 2017",Varies with device,2.3 and up
1661,Temple Run 2,GAME,4.3,8118609,62000.000000,500000000,Free,0.0,Everyone,Action,"July 5, 2018",1.49.1,4.0 and up
1663,Helix Jump,GAME,4.2,1497361,33000.000000,100000000,Free,0.0,Everyone,Action,"April 9, 2018",1.0.6,4.1 and up
1669,Zombie Hunter King,GAME,4.3,10306,50000.000000,1000000,Free,0.0,Mature 17+,Action,"August 1, 2018",1.0.8,2.3 and up
1671,Kick the Buddy,GAME,4.3,1000417,21516.529524,50000000,Free,0.0,Teen,Action,"July 5, 2018",Varies with device,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10783,Modern Counter Terror Attack – Shooting Game,GAME,4.2,340,72000.000000,50000,Free,0.0,Mature 17+,Action,"October 27, 2017",1.0,4.1 and up
10784,Big Hunter,GAME,4.3,245455,84000.000000,10000000,Free,0.0,Everyone 10+,Action,"May 31, 2018",2.8.6,4.0 and up
10787,Modern Counter Global Strike 3D,GAME,4.1,297,48000.000000,50000,Free,0.0,Teen,Action,"March 28, 2018",1.2,4.1 and up
10789,Modern Counter Global Strike 3D V2,GAME,4.0,368,48000.000000,50000,Free,0.0,Everyone 10+,Action,"March 28, 2018",1.7,4.1 and up
10803,Fatal Raid - No.1 Mobile FPS,GAME,4.3,56496,81000.000000,1000000,Free,0.0,Teen,Action,"August 7, 2018",1.5.447,4.0 and up

In [73]:
# Selecting the Action genres apps with rating > 4.2
data2[(data2["Genres"]=="Action") & (data2["Rating"]>4.2)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1659,slither.io,GAME,4.4,5234162,21516.529524,100000000,Free,0.0,Everyone,Action,"November 14, 2017",Varies with device,2.3 and up
1661,Temple Run 2,GAME,4.3,8118609,62000.000000,500000000,Free,0.0,Everyone,Action,"July 5, 2018",1.49.1,4.0 and up
1669,Zombie Hunter King,GAME,4.3,10306,50000.000000,1000000,Free,0.0,Mature 17+,Action,"August 1, 2018",1.0.8,2.3 and up
1671,Kick the Buddy,GAME,4.3,1000417,21516.529524,50000000,Free,0.0,Teen,Action,"July 5, 2018",Varies with device,4.4 and up
1693,Zombie Catchers,GAME,4.7,990491,75000.000000,10000000,Free,0.0,Everyone,Action,"May 24, 2018",1.0.27,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10636,FRONTLINE COMMANDO,GAME,4.4,1351833,12000.000000,10000000,Free,0.0,Teen,Action,"October 28, 2013",3.0.3,2.1 and up
10673,Magnum 3.0 Gun Custom SImulator,GAME,4.5,16815,59000.000000,1000000,Free,0.0,Teen,Action,"August 4, 2018",1.0404,4.0.3 and up
10781,Modern Strike Online,GAME,4.3,834117,44000.000000,10000000,Free,0.0,Teen,Action,"July 30, 2018",1.25.4,4.1 and up
10784,Big Hunter,GAME,4.3,245455,84000.000000,10000000,Free,0.0,Everyone 10+,Action,"May 31, 2018",2.8.6,4.0 and up
10803,Fatal Raid - No.1 Mobile FPS,GAME,4.3,56496,81000.000000,1000000,Free,0.0,Teen,Action,"August 7, 2018",1.5.447,4.0 and up

# Sorting

In [74]:
data2.sort_values(["App"])

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
8532,+Download 4 Instagram Twitter,SOCIAL,4.5,40467,22000.0,1000000,Free,0.00,Everyone,Social,"August 2, 2018",5.03,4.1 and up
324,- Free Comics - Comic Apps,COMICS,3.5,115,9100.0,10000,Free,0.00,Mature 17+,Comics,"July 13, 2018",5.0.12,5.0 and up
4541,.R,TOOLS,4.5,259,203.0,10000,Free,0.00,Everyone,Tools,"September 16, 2014",1.1.06,1.5 and up
4636,/u/app,COMMUNICATION,4.7,573,53000.0,10000,Free,0.00,Mature 17+,Communication,"July 3, 2018",4.2.4,4.1 and up
5940,058.ba,NEWS_AND_MAGAZINES,4.4,27,14000.0,100,Free,0.00,Everyone,News & Magazines,"July 6, 2018",1.0,4.2 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6420,감성학원 BL 첫사랑,COMICS,4.4,190,34000.0,10000,Free,0.00,Everyone,Comics,"November 17, 2017",3.2.1,3.0 and up
4362,💎 I'm rich,LIFESTYLE,3.8,718,26000.0,10000,Paid,399.99,Everyone,Lifestyle,"March 11, 2018",1.0.0,4.4 and up
2575,"💘 WhatsLov: Smileys of love, stickers and GIF",SOCIAL,4.6,22098,18000.0,1000000,Free,0.00,Everyone,Social,"July 24, 2018",4.2.4,4.0.3 and up
7559,📏 Smart Ruler ↔️ cm/inch measuring for homework!,TOOLS,4.0,19,3200.0,10000,Free,0.00,Everyone,Tools,"October 21, 2017",1.0,4.2 and up
882,🔥 Football Wallpapers 4K | Full HD Backgrounds 😍,ENTERTAINMENT,4.7,11661,4000.0,1000000,Free,0.00,Everyone,Entertainment,"July 14, 2018",1.1.3.2,4.0.3 and up

In [75]:
# Sort the data by category and then by rating
data2.sort_values(["Category","Rating"])

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
15,Learn To Draw Kawaii Characters,ART_AND_DESIGN,3.2,55,2700.000000,5000,Free,0.00,Everyone,Art & Design,"June 6, 2018",Varies with device,4.2 and up
5179,Ai illustrator viewer,ART_AND_DESIGN,3.4,486,5900.000000,100000,Free,0.00,Everyone,Art & Design,"July 26, 2018",5.7,5.0 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19000.000000,50000,Free,0.00,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
35,How to draw Ladybug and Cat Noir,ART_AND_DESIGN,3.8,564,9200.000000,100000,Free,0.00,Everyone,Art & Design,"July 11, 2018",2.1,4.1 and up
43,Paint Splash!,ART_AND_DESIGN,3.8,2206,1200.000000,100000,Free,0.00,Everyone,Art & Design;Creativity,"April 15, 2018",1.46,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7491,Fu*** Weather (Funny Weather),WEATHER,4.7,20001,21516.529524,1000000,Free,0.00,Mature 17+,Weather,"July 26, 2018",Varies with device,Varies with device
8912,Weather Forecast Pro,WEATHER,4.7,14051,8700.000000,100000,Paid,3.99,Everyone,Weather,"August 4, 2018",8.5,4.0 and up
3627,Weather forecast,WEATHER,4.8,159455,10000.000000,1000000,Free,0.00,Everyone,Weather,"May 8, 2018",1.11.93,4.4 and up
3629,Live Weather Pro,WEATHER,4.8,892,17000.000000,10000,Free,0.00,Everyone,Weather,"July 17, 2018",1.1,4.4 and up
3658,Weather Live Pro,WEATHER,4.8,17493,11000.000000,100000,Paid,4.49,Everyone,Weather,"April 20, 2018",1.3,4.4 and up

In [76]:
# Display unique value in Category column.
data2["Category"].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION'],
      dtype=object)